import type { Metadata } from "next";
import { Comforter } from "next/font/google";
import "./globals.css";

const Comforter_Font = Comforter({
  subsets: ['latin'],
  weight:'400'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Comforter_Font.className}`}
      >
        {children}
      </body>
    </html>
  );
}
